package com.seckawijoki.android_test.constant;

/**
 * Created by 瑶琴频曲羽衣魂 on 2017/6/22.
 */

public interface IntentActions {
  String BASE = "com.seckawijoki.android_test.";
  String OLD_TEST = BASE + "OLD_TEST";
  String NAVIGATION_VIEW = BASE + "NAVIGATION_VIEW";
  String TOUCH_FOR_LARGENING = BASE + "TOUCH_FOR_LARGENING";
  String DATE_GROUPED = BASE + "DATE_GROUPED";
  String MY_SERVICE_TEST = BASE + "MY_SERVICE_TEST";
  String WHETHER_IN_UI_THREAD = BASE + "WHETHER_IN_UI_THREAD";
  String LIFECYCLE = BASE + "LIFECYCLE";
  String AN_ACTIVITY = BASE + "AN_ACTIVITY";
  String A_DIALOG_ACTIVITY = BASE + "A_DIALOG_ACTIVITY";
  String DISPATCH_TEST = BASE + "DISPATCH_TEST";
  String AMAP_TEST = BASE + "AMAP_TEST";
  String SOCKET_PROGRAMMING = BASE + "SOCKET_PROGRAMMING";
  String ANIMATOR_TEST = BASE + "ANIMATOR_TEST";
  String LAUNCH_MODE = BASE + "LAUNCH_MODE";
  String BAIDU_PUSH_FLOW = BASE + "BAIDU_PUSH_FLOW";
  String COLLAPSING_TOOLBAR = BASE + "COLLAPSING_TOOLBAR";
  String SINGLE_CHOICE_RECYCLER_VIEW = BASE + "SINGLE_CHOICE_RECYCLER_VIEW";
}
