//
// Created by Seckawijoki on 2018/6/1 at 18:28 under Windows10 Professional.
//

#include <jni.h>
#ifndef SECKAWIJOKI_ANDROID_TEST_COM_SECKAWIJOKI_ANDROIDTEST_TOOL_NATIVEHELPER_H
#define SECKAWIJOKI_ANDROID_TEST_COM_SECKAWIJOKI_ANDROIDTEST_TOOL_NATIVEHELPER_H

#endif //SECKAWIJOKI_ANDROID_TEST_COM_SECKAWIJOKI_ANDROIDTEST_TOOL_NATIVEHELPER_H
